"""empty message

Revision ID: 883a83a184a0
Revises: fcc3fd176193
Create Date: 2023-04-18 15:14:10.750633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883a83a184a0'
down_revision = 'fcc3fd176193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_constraint('characters_homeworld_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('homeworld_planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('characters_homeworld_planet_id_fkey', 'planets', ['homeworld_planet_id'], ['id'])
        batch_op.alter_column('gender',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
